/* This is the code for esp32 including recive data from master device(Ardunio uno)
   Five variables (Air temperature, Air humidity, Soil humidity, Water tank weight, Pump's on/off,
   also the trend for Soil humidity which generated by Blynk GUI)
*/
#define RXD2 7
#define TXD2 8

#define BLYNK_PRINT Serial

/* Fill-in your Template ID (only if using Blynk.Cloud) */
#define BLYNK_TEMPLATE_ID "TMPL2kAnDz2Uw"
#define BLYNK_TEMPLATE_NAME "ESE519final"
#define BLYNK_AUTH_TOKEN "MuxdCZLVchxayJkTi8GQkXsEYvoQS5Km"

#include <WiFi.h>
#include <WiFiClient.h>
#include <BlynkSimpleEsp32.h>

char auth[] = BLYNK_AUTH_TOKEN;

float SoilHumidity = 11.3;
float WaterTank = 1.6; 
float AirHumidity = 78.3;
float AirTemp = 66.6; 
int PumpStatus = 1;

// Your WiFi credentials.
// Set password to "" for open networks.
char ssid[] = "sunglab";
char pass[] = "makergear";

BlynkTimer timer;

// This function is called every time the device is connected to the Blynk.Cloud
BLYNK_CONNECTED()
{
  // Change Web Link Button message to "Congratulations!"
  Blynk.setProperty(V3, "offImageUrl", "https://static-image.nyc3.cdn.digitaloceanspaces.com/general/fte/congratulations.png");
  Blynk.setProperty(V3, "onImageUrl",  "https://static-image.nyc3.cdn.digitaloceanspaces.com/general/fte/congratulations_pressed.png");
  Blynk.setProperty(V3, "url", "https://docs.blynk.io/en/getting-started/what-do-i-need-to-blynk/how-quickstart-device-was-made");
}

void setup()
{
  // Debug console
  Serial.begin(115200);
  Serial2.begin(9600, SERIAL_8N1, RXD2, TXD2);
  Blynk.begin(auth, ssid, pass);
  timer.setInterval(100L, sendSensor);
}

void sendSensor()
{
    Blynk.virtualWrite(V0, AirTemp);
    Blynk.virtualWrite(V1, AirHumidity);
    Blynk.virtualWrite(V2, SoilHumidity);
    Blynk.virtualWrite(V3, WaterTank);
    Blynk.virtualWrite(V4, PumpStatus);
}

void Read(){
  if (Serial2.available()) {
    // Read the incoming data as a string
    String data = Serial2.readStringUntil('\n');
    
    // Split the data at the comma
    int commaIndex = data.indexOf(',');
    String soilHumidityStr = data.substring(0, commaIndex);
    String waterTankStr = data.substring(commaIndex + 1);

    // Convert the split strings to float
    SoilHumidity = soilHumidityStr.toFloat();
    WaterTank = waterTankStr.toFloat();

    // Print the values
    Serial.print("Soil Humidity: ");
    Serial.println(SoilHumidity);
    Serial.print("Water Tank: ");
    Serial.println(WaterTank);
  }
}

void loop()
{
  Read();
  Blynk.run();
  timer.run();
}
